version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  drf:
    restart: always
    container_name: drf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./library:/test/library
    entrypoint: >
      bash -c "chmod +x /test/library/server-entrypoint.sh && /test/library/server-entrypoint.sh"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB=postgresql
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    depends_on:
      - db


  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./library/django_static:/test/library/django_static
    depends_on:
      - drf
    
      


